/**
 * Get currency symbol from currency code
 */
export function getCurrencySymbol(currencyCode: string | null | undefined): string {
  if (!currencyCode) return '';
  
  const currencySymbols: Record<string, string> = {
    'USD': '$',
    'EUR': '€',
    'GBP': '£',
    'JPY': '¥',
    'AUD': 'A$',
    'CAD': 'C$',
    'CHF': 'CHF',
    'CNY': '¥',
    'INR': '₹',
    'PKR': '₨',
    'AED': 'د.إ',
    'SAR': '﷼',
    'BRL': 'R$',
    'MXN': '$',
    'RUB': '₽',
    'ZAR': 'R',
    'SGD': 'S$',
    'HKD': 'HK$',
    'NZD': 'NZ$',
    'SEK': 'kr',
    'NOK': 'kr',
    'DKK': 'kr',
    'PLN': 'zł',
    'TRY': '₺',
    'THB': '฿',
    'MYR': 'RM',
    'IDR': 'Rp',
    'PHP': '₱',
    'KRW': '₩',
    'VND': '₫',
    'BGN': 'лв',
    'CZK': 'Kč',
    'HUF': 'Ft',
    'RON': 'lei',
    'ILS': '₪',
    'CLP': '$',
    'COP': '$',
    'ARS': '$',
    'PEN': 'S/',
    'EGP': 'E£',
    'NGN': '₦',
    'KES': 'KSh',
    'BDT': '৳',
    'LKR': 'Rs',
    'NPR': 'Rs',
    'MMK': 'K',
    'KHR': '៛',
    'LAK': '₭',
    'MNT': '₮',
    'KZT': '₸',
    'UAH': '₴',
    'BYN': 'Br',
    'RSD': 'дин',
    'HRK': 'kn',
    'BAM': 'КМ',
    'MKD': 'ден',
    'ALL': 'L',
    'ISK': 'kr',
    'JMD': '$',
    'TTD': '$',
    'BBD': '$',
    'BZD': '$',
    'XCD': '$',
    'AWG': 'ƒ',
    'ANG': 'ƒ',
    'GYD': '$',
    'SRD': '$',
    'FJD': '$',
    'PGK': 'K',
    'SBD': '$',
    'VUV': 'Vt',
    'WST': 'T',
    'TOP': 'T$',
    'XPF': '₣',
    'NIO': 'C$',
    'HNL': 'L',
    'GTQ': 'Q',
    'BWP': 'P',
    'ZMW': 'ZK',
    'MWK': 'MK',
    'UGX': 'USh',
    'TZS': 'TSh',
    'ETB': 'Br',
    'MAD': 'د.م.',
    'TND': 'د.ت',
    'DZD': 'د.ج',
    'LYD': 'ل.د',
    'IQD': 'ع.د',
    'JOD': 'د.ا',
    'LBP': 'ل.ل',
    'OMR': 'ر.ع.',
    'KWD': 'د.ك',
    'BHD': 'د.ب',
    'QAR': 'ر.ق',
    'IRR': '﷼',
    'AFN': '؋',
    'UZS': 'лв',
    'TJS': 'ЅМ',
    'TMT': 'm',
    'AMD': '֏',
    'GEL': '₾',
    'AZN': '₼',
    'MDL': 'L',
    'BND': '$',
    'KGS': 'с',
    'XOF': 'CFA',
    'XAF': 'FCFA',
    'DJF': 'Fdj',
    'ERN': 'Nfk',
    'SOS': 'S',
    'RWF': 'RF',
    'BIF': 'FBu',
    'CDF': 'FC',
    'AOA': 'Kz',
    'MZN': 'MT',
    'MGA': 'Ar',
    'SCR': '₨',
    'MUR': '₨',
    'CVE': '$',
    'STN': 'Db',
    'GMD': 'D',
    'GNF': 'FG',
    'SLE': 'Le',
    'LRD': '$',
    'GHS': '₵',
  };
  
  return currencySymbols[currencyCode.toUpperCase()] || currencyCode;
}

/**
 * Format price with currency symbol
 */
export function formatPrice(price: number, currencyCode: string | null | undefined): string {
  const symbol = getCurrencySymbol(currencyCode);
  return `${symbol}${price.toFixed(2)}`;
}

